repos:
  - repo: https://github.com/PyCQA/isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace