version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx.conf.d
    depends_on:
      - backend
  backend:
    build: .
    command: sh -c "pipenv run gunicorn shop.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: local-mysql
    ports:
      - "8000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "liminxi"
    command:
      # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
